name: Devel Branch Build

on:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  develBuild:
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: fedora
            version: 38
            dockernamespace: quay.io/fedora/fedora
          - os: fedora
            version: 39
            dockernamespace: quay.io/fedora/fedora
          - os: centos
            version: 7.9.2009
            dockernamespace: quay.io/centos/centos
          - os: centos-stream
            version: stream8
            dockernamespace: quay.io/centos/centos
          - os: centos-stream
            version: stream9
            dockernamespace: quay.io/centos/centos
          - os: rocky
            version: 8
            dockernamespace: quay.io/rockylinux/rockylinux
          - os: rocky
            version: 9
            dockernamespace: quay.io/rockylinux/rockylinux
          - os: almalinux
            version: 8
            dockernamespace: quay.io/almalinux/almalinux
          - os: almalinux
            version: 9
            dockernamespace: quay.io/almalinux/almalinux

    steps:
      - uses: actions/checkout@v3

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=devel" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Run CI
        run: ci/${{ matrix.os }}.sh
